version: '3'
services:
    mc:
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        expose:
            - '25575'
        volumes:
            - mc:/data
            - ./restore:/restore:ro
        environment:
            EULA: "TRUE"
            MAX_MEMORY: 3G
            ENABLE_RCON: "true"
            VERSION: "1.14.4"
        env_file:
            - minecraft.env
        restart: always

    backup:
        build: https://github.com/nekoruri/docker-mc-backup.git
        volumes:
            - mc:/data:ro
            - backups:/backups
        links:
            - mc
        environment:
            RCON_HOST: mc
        env_file:
            - minecraft.env

volumes:
    mc:
    backups:
