version: '3'
services:
    mc:
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        expose:
            - '25575'
        volumes:
            - mc:/data
            - ./restore:/restore:ro
        environment:
            EULA: "TRUE"
            MAX_MEMORY: 3G
            ENABLE_RCON: "true"
            VERSION: "1.16.1"
        env_file:
            - minecraft.env
        restart: always
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                fluentd-async-connect: "true"
                tag: "docker.{{.Name}}"

    backup:
        build: https://github.com/nekoruri/docker-mc-backup.git
        volumes:
            - mc:/data:ro
            - backups:/backups
        links:
            - mc
        environment:
            RCON_HOST: mc
        env_file:
            - minecraft.env
        restart: always
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                fluentd-async-connect: "true"
                tag: "docker.{{.Name}}"

    fluentd:
        build:
            context: ./fluentd/
        ports:
            - 24224:24224
        volumes:
            - fluentd_buffer:/fluentd/buffer:rw
        env_file:
            - minecraft.env
        restart: always

volumes:
    mc:
    backups:
    fluentd_buffer:
