version: '3'
services:
    mc:
        image: itzg/minecraft-server:java21
        ports:
            - 49357:25565
        expose:
            - '25575'
        volumes:
            - mc:/data
            - ./restore:/restore:ro
        environment:
            EULA: "TRUE"
            MAX_MEMORY: 3G
            ENABLE_RCON: "true"
            VERSION: "1.20.6"
            WORLD: "/restore/world"
        env_file:
            - minecraft.env
        restart: always
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                fluentd-async-connect: "true"
                tag: "docker.{{.Name}}"

    backup:
        image: itzg/mc-backup
        volumes:
            - mc:/data:ro
            - backups:/backups
            - ./rclone.config:/config/rclone/rclone.conf:ro
        links:
            - mc
        environment:
            RCON_HOST: mc
            PRUNE_BACKUPS_DAYS: -1
        env_file:
            - minecraft.env
        restart: always
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "localhost:24224"
                fluentd-async-connect: "true"
                tag: "docker.{{.Name}}"

    fluentd:
        build:
            context: ./fluentd/
        ports:
            - 24224:24224
        volumes:
            - fluentd_buffer:/fluentd/buffer:rw
        env_file:
            - minecraft.env
        restart: always

volumes:
    mc:
    backups:
    fluentd_buffer:
